# Generated by Django 5.2.4 on 2026-02-17 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(default='ordered', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reply', models.TextField()),
                ('date', models.DateField()),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('CART', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('BILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bill')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=150)),
                ('issue', models.TextField()),
                ('service_date', models.DateField()),
                ('status', models.CharField(default='booked', max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='SERVICEBOOKING',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicebooking'),
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='SERVICECENTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicecenter'),
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('license_proof', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='SHOWROOM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.showroom'),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('SERVICECENTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicecenter')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='SPAREPART',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sparepart'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('fuel_type', models.CharField(max_length=50)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='sparepart',
            name='MODEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('engine_cc', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('MODEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('SHOWROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.showroom')),
                ('VARIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclevariant')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('SHOWROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.showroom')),
                ('VARIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclevariant')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('SHOWROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.showroom')),
                ('VARIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclevariant')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('SHOWROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.showroom')),
                ('VARIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiclevariant')),
            ],
        ),
    ]
