# Generated by Django 5.2.4 on 2026-02-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_order_cart_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_charge', models.IntegerField()),
                ('spare_charge', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='unpaid', max_length=20)),
                ('SERVICE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='myapp.servicebooking')),
            ],
        ),
    ]
