# Generated by Django 5.2.4 on 2026-02-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_servicebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='BILL',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicebill'),
        ),
    ]
