"""
URL configuration for showroom project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('login_get/',views.login_get),
    path('login_post/',views.login_post),
    path('adminhome/',views.adminhome),
    path('addcompany_get/',views.addcompany_get),
    path('addcompany_post/',views.addcompany_post),
    path('adminview_company/',views.adminview_company),
    path('edit_company_get/<id>',views.edit_company_get),
    path('edit_company_post/',views.edit_company_post),
    path('admindelete_company/<id>',views.admindelete_company),
    path('add_vehiclemodel_get/<id>',views.add_vehiclemodel_get),
    path('add_vehiclemodel_post/',views.add_vehiclemodel_post),
    path('adminview_vehiclemodel/',views.adminview_vehiclemodel),
    path('edit_vehiclemodel_get/<id>',views.edit_vehiclemodel_get),
    path('edit_vehiclemodel_post/',views.edit_vehiclemodel_post),
    path('admindelete_vehiclemodel/<id>',views.admindelete_vehiclemodel),
    path('add_variant/<id>',views.add_variant_get),
    path('add_variant_post/',views.add_variant_post),
    path('view_variant/',views.view_variant),
    path('edit_variant/<id>',views.edit_variant_get),
    path('edit_variant_post/',views.edit_variant_post),
    path('delete_variant/<id>',views.delete_variant),
    path('verifyshowroom/<id>',views.verifyshowroom),
    path('viewShowrooms/',views.viewShowrooms),
    path('viewapprovedshowrooms/',views.viewapprovedshowrooms),
    path('viewservicecenter/',views.viewservicecenter),
    path('viewusers/',views.viewusers),
    path('viewfeedback/',views.viewfeedback),
    path('sendreply/<id>',views.sendreply),
    path('sendreply_post/',views.sendreply_post),
    path('admin_changePassword_get/',views.admin_changePassword_get),
    path('admin_changePassword_post/',views.admin_changePassword_post),
    path('logout_get/',views.logout_get),
    path('showroomsignup_get/',views.showroomsignup_get),
    path('showroom_signup/',views.showroom_signup),
    path('showroomhome/',views.showroomhome),
    path('showroomview_profile/',views.showroomview_profile),
    path('editprofile_gets/',views.editprofile_gets),
    path('showroom_editprofile/',views.showroom_editprofile),
    path('addservicecenter_get/',views.addservicecenter_get),
    path('showroom_add_servicecenter/',views.showroom_add_servicecenter),
    path('showroom_view_servicecenter/',views.showroom_view_servicecenter),
    path('showroom_delete_servicecenter/<id>',views.showroom_delete_servicecenter),
    path('showroom_edit_servicecenter_get/<id>',views.showroom_edit_servicecenter_get),
    path('showroom_edit_servicecenter_post/',views.showroom_edit_servicecenter_post),
    path('showroomviewmodel/',views.showroomviewmodel),
    path('showroomviewvarient/<id>',views.showroomviewvarient),
    path('addshowroomstock_get/<id>',views.addshowroomstock_get),
    path('addstock_post/',views.addstock_post),
    path('showroom_viewstock/',views.showroom_viewstock),
    path('edit_stock_get/<id>',views.edit_stock_get),
    path('delete_stock/<id>',views.delete_stock),
    path('editstock_post/',views.editstock_post),
    path('addprice_post/',views.addprice_post),
    path('editprice_post/',views.editprice_post),
    path('addprice_get/<id>',views.addprice_get),
    path('viewprice/<id>',views.viewprice),
    path('editprice_get/<id>',views.editprice_get),
    path('deleteprice/<id>',views.deleteprice),
    path('acceptride_request/<id>',views.acceptride_request),
    path('rejectride_request/<id>',views.rejectride_request),
    path('showroomview_price/',views.showroomview_price),
    path('viewrideRequest/',views.viewrideRequest),
    path('view_accepted_rideRequest/',views.view_accepted_rideRequest),
    path('view_vehicleBooking/',views.view_vehicleBooking),
    path('showroom_changePassword_get/',views.showroom_changePassword_get),
    path('showroom_changePassword_post/',views.showroom_changePassword_post),
    path('servicecenterhome/',views.servicecenterhome),
    path('servicecenterviewmodels/',views.servicecenterviewmodels),
    path('servicecenterprofile/',views.servicecenterprofile),
    path('addsparepart_get/<id>', views.addsparepart_get),
    path('addsparepart_post/', views.addsparepart_post),
    path('viewsparepart/', views.viewsparepart),
    path('editspareparts_get/<id>', views.editspareparts_get),
    path('editsparepart_post/', views.editsparepart_post),
    path('delete_sparepart/<id>', views.delete_sparepart),
    path('servicevieworders/', views.servicevieworders),
    path('viewservicebooking/', views.viewservicebooking),
    path('update_service/<id>', views.update_service),
    path('viewbill/', views.viewbill),
    path('view_review/', views.view_review),
    path('servicecenterchangepassword_get/', views.servicecenterchangepassword_get),
    path('service_changePassword_post/', views.service_changePassword_post),
    path('userhome/', views.userhome),
    path('usersignup_get/', views.usersignup_get),
    path('usersignup_post/', views.usersignup_post),
    path('viewprofile/', views.viewprofile),
    path('editprofile_get/', views.editprofile_get),
    path('editprofile_post/', views.editprofile_post),
    path('userviewcompany/', views.userviewcompany),
    path('userviewmodels/<id>', views.userviewmodels),
    path('userviewvarients/<id>', views.userviewvarients),
    path('userviewavailableshowroom/<id>', views.userviewavailableshowroom),
    path('send_riderequest/<int:showroom_id>/<int:variant_id>/',views.usersend_riderequest,name='send_riderequest'),
    path('userview_testrideBooking/',views.userview_testrideBooking),
    path('book_vehicle/<int:showroom_id>/<int:variant_id>/',views.user_book_vehicle),
    path('userviewbooking/',views.userviewbooking),
    path('userviewspareparts/',views.userviewspareparts),
    path('update_vehicle_booking_status/<int:id>/<str:status>/', views.update_vehicle_booking_status),
    path('spareparts/',views.userviewspareparts),
    path('addtocart/<int:id>/', views.add_to_cart),
    path('view_cart/', views.view_cart),
    path('placeorder/', views.place_order),
    path('payment_success/', views.payment_success),
    path('order_status/', views.order_status),
    path('payorder/<int:id>/', views.pay_existing_order),
    path('increase_qty/<int:id>/', views.increase_qty),
    path('decrease_qty/<int:id>/', views.decrease_qty),
    path('book_service/<int:id>/', views.book_service),
    path('book_service_post/', views.book_service_post),
    path('view_upcoming_services/', views.view_upcoming_services),
    path('userview_servicecenter/',views.userview_servicecenter),
    path('viewservicebooking/', views.viewservicebooking, name='viewservicebooking'),
    path('update_service/<int:id>/', views.update_service, name='update_service'),
    path('generate_bill/<int:id>/', views.generate_bill, name='generate_bill'),
    path('view_bill/<int:id>/', views.view_bill, name='view_bill'),
    path('user_view_services/', views.user_view_services, name='user_view_services'),
    path('user_view_bill/<int:id>/', views.user_view_bill, name='user_view_bill'),
    path('pay_bill/<int:id>/', views.pay_bill, name='pay_bill'),
    path('add_review/<int:id>/', views.add_review, name='add_review'),
    path('view_service_history/', views.view_service_history, name='view_service_history'),
    path('bill_payment_success/', views.bill_payment_success, name='bill_payment_success'),
    path('add_review_post/', views.add_review_post, name='add_review_post'),
    path('user_changePassword_get/', views.user_changePassword_get, name='user_changePassword_get'),
    path('user_changePassword_post/', views.user_changePassword_post, name='user_changePassword_post'),
    path('send_feedback/',views.send_feedback),
    path('send_feedback_post/',views.send_feedback_post),
    path('view_feedback/',views.view_feedback),
    path('admin_view_feedback/',views.admin_view_feedback),
    path('forgotpassword_post/',views.forgotpassword_post),
    path('forgot_password_get/',views.forgot_password_get),
    path('customer_order_history/',views.customer_order_history),
    path('reply_feedback/<int:id>/',views.reply_feedback),
    path('create_admin/',views.create_admin)





]
